APP_URL=https://www.mshwarak.org/
FCM_PROJECT_ID=mashwarak-896b4
FCM_API_KEY=AIzaSyDcHEyGKE6rBWIN7jUCihkxSxwd8hEYGyg
FCM_APP_ID=1:327243985884:android:c33a35eb234dff50d79519
FCM_SENDER_ID=327243985884
